plugins {
    id 'java'
    id 'maven-publish'
}

archivesBaseName = "${build_file_name}-Common-${minecraft_version}"

dependencies {
    compileOnly("org.spongepowered:mixin:0.8.5")
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    compileOnly group: 'com.esotericsoftware.yamlbeans', name: 'yamlbeans', version: '1.15'
}


processResources {

    def buildProps = project.properties.clone()

    filesMatching(['pack.mcmeta']) {

        expand buildProps
    }
}

